[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AD0D1BAD50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b16abe4c524f5dc6e5df92ec75ec1498
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AD0D1BB250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b16abe4c524f5dc6e5df92ec75ec1498
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AD0D20C640>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b16abe4c524f5dc6e5df92ec75ec1498