[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022FBCE9AD50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/41cb467bccb13f8f4255e6c366e7cdd0
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022FBCE9B250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/41cb467bccb13f8f4255e6c366e7cdd0
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022FBCEE8640>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/41cb467bccb13f8f4255e6c366e7cdd0