[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002981915AD50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c9525731b00a4651f9fa737d8cc7ac03
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002981915B250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c9525731b00a4651f9fa737d8cc7ac03
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000298191A8640>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c9525731b00a4651f9fa737d8cc7ac03